# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a35738ffa744cee56dfd82f5276437258e3ca07047944695950386b7c59bfd1718bcbe25f37e68be89b6419427bc0d727404a67773fbdce1fba11acb129a93b

test:
  secret_key_base: b0c529b553cc8171f33bd1b192416fd52852abe14f50eaa5fabf5af177ff28c6ab15dd677c1059dfd773aeb8208289c19e5ca2eb55ae5fed0d8ecfb97918307a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
